### ISSUE TITLE
Enable coverage report in README

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection#138]
**Is your feature request related to a problem? Please describe.**
Similar to this: https://github.com/opendistro-for-elasticsearch/index-management/commit/f74fa1afad716732f92dbd077746cbe146a71ebd

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yizheliu-amazon** [comment]
Addressed in PR: https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/199
