### ISSUE TITLE
Enable support high cardinality in anomaly detection

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opendistro-for-elasticsearch/anomaly-detection#147]
As data grow, we see more and more need for a solution that could handle large volumes of high dimensional data and detect anomalies in real-time. The first release of real-time anomaly detection focuses on detecting outliers on specific fields with aggregations. However, a number of our customers leveraging Elasticsearch for their observability use cases comprising operational intelligence, application performance management, and security data, have asked for support for high cardinality. High cardinality information (such has request ID, ASIN, IP address, user id) is most important for debugging and isolating a problem to a unique system or ID. We request to support high-cardinality in AD to fill this gap.

(Details to be added)

**Comment by ylwu-amzn** [comment]
We have released high cardinality anomaly detector, check ODFE doc for more details: https://opendistro.github.io/for-elasticsearch-docs/docs/ad/
