### ISSUE TITLE
Create setting's doc

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection#149]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create a settings doc like https://opendistro.github.io/for-elasticsearch-docs/docs/knn/settings/

**Describe alternatives you've considered**

**Additional context**

**Comment by ylwu-amzn** [comment]
Done. Check ODFE doc https://opendistro.github.io/for-elasticsearch-docs/docs/ad/settings/
