### ISSUE TITLE
Add coverage report

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection#155]
**Describe the solution you'd like**
Similar to https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/commit/e926ce9107c878cbe96e18b616dfdcfeb1061568 and https://github.com/opendistro-for-elasticsearch/alerting/commit/fed0a094056ddf1c2ff6ed6fa06fa96ad6484bae

**Describe alternatives you've considered**

**Additional context**

**Comment by ylwu-amzn** [comment]
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/199
