### ISSUE TITLE
[RFC] Anomaly Detection CLI

### ISSUE THREAD

**Issue by VijayanB** [opendistro-for-elasticsearch/anomaly-detection#186]
The purpose of this issue is to capture feedback and comments regarding the AD CLI project's request for comments

https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/master/cli/rfc-adcli.md

**Comment by ylwu-amzn** [comment]
Close this issue as we have moved to ODFE CLI https://github.com/opendistro-for-elasticsearch/odfe-cli.
