### ISSUE TITLE
Change default shingle size to 1

### ISSUE THREAD

**Issue by wnbts** [opendistro-for-elasticsearch/anomaly-detection#193]
**Is your feature request related to a problem? Please describe.**
Current default shingle size on data streams is set to be 8. For many real-world data streams that are not dense, shingling fails and anomaly detection is aborted.

**Describe the solution you'd like**
Shingle size 1 is the most general default setting for anomaly detection on data streams.

**Comment by kaituo** [comment]
We don't have a conclusion for this yet.  I feel the right solution is to decide shingle size based on data.  For example, set shingle size to 1 if the data is sparse; otherwise, keep it 8.

**Comment by wnbts** [comment]
even data is dense, the right shingle size is not necessarily 8 or larger than 1.

**Comment by kaituo** [comment]
Right, that's what you guys are still working on.

**Comment by wnbts** [comment]
Since that research will take a few, maybe two, months and by no means guarantee a solution, is it worth making this change to not further block more users?

**Comment by kaituo** [comment]
We can make the change without affecting users with dense data.  We can still help them find contextual anomaly.

How about this?
After cold start sampling and creating shingles, we check the ratio: expected shingle number given dense data/ actual shingles: if the ratio is less than 25%, using shingle size 1 or exponential smooth; otherwise use default 8 + rcf impute/nearest neighbor.  expected shingle number given dense data = # samples + shingle size - 1

**Comment by wnbts** [comment]
There are two things regarding contextual anomalies. First, their definition and evaluation are unclear so far. They can be mixed with false positives based on current benchmarking. Second, the real contextual anomalies (in the context of days/weeks/months) are not captured by a small shingle size. For example, a day of 5-min data points requires a shingle of 288. 8 is not much different from 1.

Two issues with the proposal. First, the density of a data stream can decides the max shingle size but not the shingle size. Second, consider the data stream changes density over time.

The current plan is first revert shingle size to 1 and second, with a clear definition and understanding of contextual anomalies and a verified way to measure and benchmark them, roll out new changes to detect contextual anomalies.

**Comment by kaituo** [comment]
> First, their definition and evaluation are unclear so far. 
For shingle's definition, let me quote Sudipto:"Shingle size corresponds to “how much data do I need to see to predict the next value".  For their evaluation, precision and recall are what you have been doing all along.  What else are you thinking?

> They can be mixed with false positives based on current benchmarking. 
No doubt.

> Second, the real contextual anomalies (in the context of days/weeks/months) are not captured by a small shingle size. For example, a day of 5-min data points requires a shingle of 288. 8 is not much different from 1.
How do you come up with the 288 number?  I know there are 288 different 5 min interval in a day.  Of course, 40 mins (or knowing the last 40 mins) we cannot always recreate the pattern.  How do you know 8 is not much different from 1?  Other factors can come into play here.  For example, the number of samples and number of trees.  512 samples may be better than 256.  10 may have more noise than 100 trees.

> Two issues with the proposal. First, the density of a data stream can decides the max shingle size but not the shingle size. 
I don't understand.  My intuition is: say I have 8 samples, I expect to have 5 shingles.  But if this gives me no shingle at all, this means shingle does not help much.  I revert back to simpler modeling methods.

> Second, consider the data stream changes density over time.
True.  

> The current plan is first revert shingle size to 1 and second, with a clear definition and understanding of contextual anomalies and a verified way to measure and benchmark them, roll out new changes to detect contextual anomalies.
I am not convinced of this plan.  Shingle size 1 for all kinds of data is too weak.  It may look easy to set in to 1 now, but the customers will complain with the noise. 

Another idea would be to keep the default to be 1 and let customer define shingle size on Kibana.  Tell them small shingle make the model susceptible to minor fluctuations in the data, and bigger shingle is more computation-intensive and not necessarily better.

**Comment by wnbts** [comment]
Can the proposal be implemented in two steps - first, set default to 1 and second, if customer requests customized shingle size, and then add it? Or, it must be implemented together.

**Comment by kaituo** [comment]
I still prefer my first idea.  The second idea has drawbacks:
1.  not sure UX would approve since it is hard for users to give a correct shingle size.
2. we have one more knob.
3. this is short-term solution, but requires both backend and front end changes. It is not worth it.

Why don't you like my first idea?

3rd idea: we keep default shingle size 8 and use rcf impute (it is actually the same code path of forecasting).  We can use the imputed point to call getAnomalyScore, but don't use it to update the forest.

**Comment by wnbts** [comment]
the issues of the initial suggestion have been called out. just to reiterate, using as many as possible is not desired while the goal is to use as many as necessary. big is not equivalent to better. for example, a data stream is results of coin flips, either 0 or 1, a single value of 2 is an anomaly and shingling smoothing can has an negative effect. the larger the shingle size, the more likely the anomaly is ignored. A more practical example is cpu utilization, a value closer to 100 is an anomaly while a contextual anomaly say an unexpected drop from 80 to 20 is not an issue. also just for the record, i don't `like` or `dislike` it.

regarding the second one, i don't see them drawbacks.
1. if customers want this, ux should work it out.
2. one knob can also be one feature.
3. since workbench will customers to try different shingle sizes and pick the one for real time use. the two feature will converge on allowing customization so this work won't be throwaway.

regarding the third one. there are multiple issues with it. first, imputed results as input is for exception, not for primary use. the results are at best similar to those from single points with X larger model size. second, not updating the model with imputed input will cause models to become stale, particularly on a sparse data stream. last, data might be too sparse for shingles that the model cannot initial training data to impute new data with.

**Comment by kaituo** [comment]
> the issues of the initial suggestion have been called out. just to reiterate, using as many as possible is not desired while the goal is to use as many as necessary. big is not equivalent to better. for example, a data stream is results of coin flips, either 0 or 1, a single value of 2 is an anomaly and shingling smoothing can has an negative effect. the larger the shingle size, the more likely the anomaly is ignored. A more practical example is cpu utilization, a value closer to 100 is an anomaly while a contextual anomaly say an unexpected drop from 80 to 20 is not an issue. also just for the record, i don't like or dislike it.

I agree with the reasoning.  shingle size 8 is not perfect and the final solution.  8 is a compromise before we can implement a long-term smart plan out for dense time series.  

> regarding the second one, i don't see them drawbacks.

    if customers want this, ux should work it out.
    one knob can also be one feature.
    since workbench will customers to try different shingle sizes and pick the one for real time use. the two feature will converge on allowing customization so this work won't be throwaway.

I am not sure normal customer wants it (advanced users may need it).  We are trying hard to eliminate all configuration in the one-click project.  Now we add one more challenging one.  I feel normal users would just either select a not too small and not too big value (say 4 or 8) or leave it as 1 by default.

The knob is a feature for advanced users.  For most users, it is a burden or sth they ignore.

I agree workbench might expose it as an advanced setting and it won't be a throwaway.  


> regarding the third one. there are multiple issues with it. first, imputed results as input is for exception, not for primary use. the results are at best similar to those from single points with X larger model size. second, not updating the model with imputed input will cause models to become stale, particularly on a sparse data stream. last, data might be too sparse for shingles that the model cannot initial training data to impute new data with.

Imputation is mostly good for dense and irregularly sampled data, not for sparse data.  I propose this mostly for a short-term solution not worrying about shingle size.

**Comment by wnbts** [comment]
resolving as the new feature allows customization
