### ISSUE TITLE
Create multi-node integ test

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection#194]
**Is your feature request related to a problem? Please describe.**
Our current integ or rest tests are all using single node.  We should have multi-node test.

**Comment by weicongs-amazon** [comment]
This is still needed. The #201 PR can't work for remote docker cluster. Need create a new one with local testing, similar as: https://github.com/opendistro-for-elasticsearch/alerting/blob/master/.github/workflows/multi-node-test-workflow.yml

**Comment by weicongs-amazon** [comment]
PR is merged.
