### ISSUE TITLE
Is there recommended node spec for this feature?

### ISSUE THREAD

**Issue by HagunKim** [opendistro-for-elasticsearch/anomaly-detection#205]
As i see this feature use machine learning, is there recommended node spec?
I wonder where the ML is run if I install ES as master node and data node.

**Comment by wnbts** [comment]
Thanks for your interest in anomaly detection.

1. With the feature built to be lightweight, your cluster that stores the data should be sufficient to handle the workloads of a small number of detectors, say 50. If hundreds of more detectors are added and more resources are needed, the system can scale out by adding more nodes.
2. ML workload is run on data nodes.

**Comment by wnbts** [comment]
I will close this issue in a day if there are no more questions or issues.

**Comment by HagunKim** [comment]
> I will close this issue in a day if there are no more questions or issues.

Many thanks for your answer.
