### ISSUE TITLE
Add feature name when invalid search query exception is thrown 

### ISSUE THREAD

**Issue by yizheliu-amazon** [opendistro-for-elasticsearch/anomaly-detection#218]
When [INVALID_SEARCH_QUERY_MSG](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/cd3bdaea465cabb0d72a76df14c5ea093a0d5080/src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java#L28) is thrown, name of feature which failed parsing is not returned in exception, it is hard for front-end to tell which feature has such issue and will cause confusion to user.

Also, from my understanding,  INVALID_SEARCH_QUERY_MSG is not likely to be thrown during `getFeatureSamplesForPeriods ()`(used in [place 1](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/92a586718f93a9ab934169cab0aca42c8641f4d9/src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java#L170), [place 2](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/92a586718f93a9ab934169cab0aca42c8641f4d9/src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java#L363)), as this can only be caught when feature aggregation query has invalid syntax which fails parsing of it, but such invalid syntax can be caught when feature is created/updated. There is even no chance for `getFeatureSamplesForPeriods()`.

**Comment by yizheliu-amazon** [comment]
@wnbts Do you have any idea on in which scenario the exception with INVALID_SEARCH_QUERY_MSG can be triggered, and how to trigger it during front end test?

**Comment by wnbts** [comment]
I am confused about this issue.
1. Is the query actually valid? If yes, this error is not expected. If no, the error is expected.
2. Since it is clear the error is caused by invalid query, using an invalid query can reproduce the issue.

**Comment by yizheliu-amazon** [comment]
> I am confused about this issue.
> 
> 1. Is the query actually valid? If yes, this error is not expected. If no, the error is expected.
> 2. Since it is clear the error is caused by invalid query, using an invalid query can reproduce the issue.

The thing is it is unlikely to put invalid query into detector. If request is sent to create/update detector with invalid feature query, it will fail. It looks to me the error may never happen, as it is caught when IOException is thrown during `getFeatureSamplesForPeriods()`

**Comment by wnbts** [comment]
Is the feature query a custom expression?

Have you seen this error?

It seems you are suggesting there is an issue where the feature query is correct but IOException is still thrown?

**Comment by yizheliu-amazon** [comment]
I have never seen this error, that is why I have such question: in which scenario this error will be returned, in another word, in which case IOException will be thrown inside `getFeatureSamplesForPeriods()`

I tried to put invalid query expression(such as wrong JSON syntax) into 1 detector, but create/update detector API doesn;t allow me to do that.

**Comment by wnbts** [comment]
I see now.

Although it looks like possible from that part of code, there is no known/expected way to trigger it from normal use. The reason why the code is looking like that is the underlying layer of code is threatening with a checked exception so the upper layer of dependency must choose to handle it or further raise it, the former of which is chosen to not further escalate a low-level error. That's another reason not to use checked exceptions.

So I don't think you need to particularly worry about that possibility for that might be simply impossible.

Of course, if someone tries very hard, say directly writing a document to the index bypassing api and validation, the error could be seen from that part, if it has not already seen elsewhere by then. It just isn't an issue for normal users.

**Comment by yizheliu-amazon** [comment]
I see. It makes sense to me. Closing it now.
