### ISSUE TITLE
SNAPSHOT jar of the anomaly-detection plugin 

### ISSUE THREAD

**Issue by WassimDhib** [opendistro-for-elasticsearch/anomaly-detection#23]
Hi,

I'd like to test the plugin.
Can you publish a SNAPSHOT jar of the anomaly-detection plugin ?

**Comment by jngz-es** [comment]
Hi WassimDhib,

Thank you for being interested in anomaly detection plugin. We are preparing the snapshot jar and will publish it soon. Anyway, you can also follow the build section in readme to build a snapshot jar if you want to try now.

**Comment by WassimDhib** [comment]
Hi @jngz-es 

I built the anomaly-detection plugin, it's now running in the cluster and I can create a detector (with api).

But still can't create a detector via kibana ui (alert plugin) 
I don't see the option "Define using Anomaly detector" when creating a monitor.

Hox can I add the detector to a monitor ?

**Comment by jngz-es** [comment]
Hi WassimDhib,

Currently AD plugin is being developed and with alpha version which needs a specific alerting plugin version - opendistro-1.2-alpha. You need to reinstall alerting plugin with this version to create AD monitor.

**Comment by WassimDhib** [comment]
Hi,

Thank you.
I built those es/kibana plugins and it's now working.
