### ISSUE TITLE
[BUG] Not able to set a filter in the detector

### ISSUE THREAD

**Issue by mario-purestake** [opendistro-for-elasticsearch/anomaly-detection#230]
**Describe the bug**
Hello everybody! My team is trying the AD plugin with our data and we are facing an issue when setting a filter in the detector. 

First we tried to set a very basic detector, with no filters, 1min interval and 0 minute delay. The feature aggregation was done with a Custom expression to perform a count on a field. So far the results were as expected, we were able to see the **Anomaly Preview** when defining the feature and the Feature output was around 90K.

```
{
    "aggregation_name": {
        "value_count": {
            "field": "Field.keyword"
        }
    }
}
```

![image](https://user-images.githubusercontent.com/66425016/93118682-eedf8080-f6c0-11ea-93ee-54eae4b83c72.png)

However, when we tried to filter the items from the index, the Feature output in the preview dropped to 0, even when the filter was _Constant_Value is Value_ (that is true for every document in the index).

![image](https://user-images.githubusercontent.com/66425016/93118810-1df5f200-f6c1-11ea-9492-4d7e4f4d7a41.png)

Doing the same search using the Discover section, we have 94K documents indexed in the last minute, so I don't think it's a problem of lacking data in that range.

![image](https://user-images.githubusercontent.com/66425016/93119195-aa081980-f6c1-11ea-9845-4e17b59dfbf2.png)

**To Reproduce**
1. Create a new detector.
2. Set an always true condition filter for the data.
3. Create a feature for the detector using the Custom Expression provided above.
4. Click on Preview Anomalies.

**Expected behavior**
The graph shows a feature output with the same value as without filter.

Any idea what's causing this? The plugin seems very promising, we really want to make it work!

**Comment by wnbts** [comment]
Hi Mario, thanks for using the product and reporting this issue!

This issue sounds the same as a known [issue](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/issues/258). And the [fix](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/277) has been merged.

**Comment by ylwu-amzn** [comment]
@mario-purestake  no updates for more than 3 months, will close this issue. Feel free if you have more questions.
