### ISSUE TITLE
[BUG] Detector not working with data type "text"

### ISSUE THREAD

**Issue by farooqdevops** [opendistro-for-elasticsearch/anomaly-detection#330]
**Describe the bug**
anomaly detector not working for field of type "text". However, only fields with type integer seems to work fine. Is it possible to change that behavior/setting of anomaly detector or we are forced to change the data type of source?

**Expected behavior**
Anomaly dectection should create a detector with field of type "text"

**Screenshots**
![anomaly_detection](https://user-images.githubusercontent.com/64216600/102057347-7343bb80-3df6-11eb-8fd1-f348c68a5938.png)

**Desktop (please complete the following information):**
AWS hosted ES cluster version ES 7.4

**Failed detector for this filter**

`{
    "aggregation_name": {
        "max": {
            "field": "response_code"
        }
    }
}`

type of response_code is "t" from discover tab of kibana. It isn't listed in field options to make anomaly detector. Only some fields with data_type of integer are shown which i am not interested. When i use custom expression, it doesn't work and detector remains stuck in initializing step. Is there any workaround to use anomaly detector so it work with other data types as well ?

**Comment by ylwu-amzn** [comment]
Check Elasticsearch document, max aggregation is
> A single-value metrics aggregation that keeps track and returns the maximum value among the numeric values extracted from the aggregated documents
