### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bolemebrige** [opendistro-for-elasticsearch/anomaly-detection#338]
I installed anomaly detection plugin on elasticsearch 7.10.0 with basic license and it gives me the following error: "Unable to get all detectors."
Also alerting plugin gives me "Failed to get the alerts [security_exception] action [indices:data/read/search] is unauthorized for user [_system]".

Is it maybe problem with activated xpack or something else?

**Comment by saratvemulapalli** [comment]
Hi @bolemebrige, with introduction of Open Distro 1.11 we have introduced plugin security enabled with Open Distro Security Plugin.

You need to assign the right permissions to create/modify/delete detectors and monitors (for alerting).
Please see public documentation: 
1. Anomaly Detection: https://opendistro.github.io/for-elasticsearch-docs/docs/ad/security/
2. Alerting: https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/security/

Let me know if you have any follow up questions.

**Comment by dumitrascuSorin** [comment]
I have the same issue as @bolemebrige 
I'm running the [Elastic stack 7.10.0 on Docker using TLS](https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html#get-started-docker-tls). 
I installed the Standalone Elasticsearch plugin for Job Scheduler, Alerting and Anomaly Detection, together with their corresponding Kibana standalone plugins (Alerting and Anomaly Detection).
When navigating to the Alerting page in Kibana, I'm getting the same error message popup as @bolemebrige.
I cannot install the Security plugin to manage the permissions because the installation is failing with the following message:
 ```
java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
 Likely root cause: ElasticsearchException[opendistro_security.ssl.transport.keystore_filepath or opendistro_security.ssl.transport.server.pemcert_filepath and opendistro_security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.]
```

**Comment by saratvemulapalli** [comment]
@dumitrascuSorin Trying to understand the problem. So you are experiencing problems accessing Anomaly Detection and Alerting when Open Distro Security plugin is not installed?

For the second part of the question, probably your security config has some part of it missing. We can reach out to the security plugin to confirm.

**Comment by bolemebrige** [comment]
Yes, I use elastics version of elasticsearch and kibana with opendistro plugins. 
Also for security functionalities  I have x-pack enabled.

**Comment by saratvemulapalli** [comment]
@bolemebrige we already have predefined roles for Anomaly Detection and Alerting but that is only in Open Distro Security plugin (Elasticsearch plugin). 

Unfortunately if you are using x-pack enabled security, you have to manually create roles. 
Here is the doc link to pre-defined roles in Open Distro Security: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#predefined-roles

**Comment by saratvemulapalli** [comment]
Please reopen if you have any other questions.
