### ISSUE TITLE
[BUG] Can't delete a detector with no existing model configuration

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/anomaly-detection#373]
**Describe the bug**

When creating a detector's configuration without creating a model configuration, the detector cannot be deleted. Returns error that seems to be related to starting the detector for some reason:
```
DELETE _opendistro/_anomaly_detection/detectors/<detectorId>
{
  "error" : {
    "root_cause" : [
      {
        "type" : "status_exception",
        "reason" : "Can't start detector job as no features configured"
      }
    ],
    "type" : "status_exception",
    "reason" : "Can't start detector job as no features configured"
  },
  "status" : 400
}
```

**To Reproduce**
1. Create a detector with no model configuration
2. Try to delete it

**Expected behavior**
The detector is deleted

**Comment by saratvemulapalli** [comment]
Interesting.. how did we catch this ? Also is this flow from AD Kibana or the API?

**Comment by ohltyler** [comment]
API. Just noticed it surfaced on Kibana when testing the different flows. I can't imagine this has been an existing bug but it is possible, kind of an edge case.

**Comment by saratvemulapalli** [comment]
I tested it on ODFE 1.12, it works fine. Probably a small regression in ODFE 1.13.
We should add an integration test for this so that we dont hit this anymore.
