### ISSUE TITLE
Question: Machine Learning -  Node Heap Usage  

### ISSUE THREAD

**Issue by Kerudal** [opendistro-for-elasticsearch/anomaly-detection#393]
Hello! My team and I are using Anomaly Detection as a SIEM tool but we have accoutered several problems with our platform. 

We are wondering why our coordinator nodes kept  falling periodically. Here is a sample of different logs encountered when one of the node fell : 
- `[2021-03-02T14:44:42,574][ERROR][c.a.o.s.s.h.n.OpenDistroSecuritySSLNettyHttpServerTransport] [KBN_0] Exception during establishing a SSL connection: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space 
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space`
- `[2021-03-02T14:45:02,191][WARN ][o.e.m.j.JvmGcMonitorService] [KBN_0] [gc][18279] overhead, spent [3.2s] collecting in the last [3.2s]`

## Here is the Kibana & Elasticsearch structure we have : 
- 2 *coordinator* nodes (installed on Kibana VMs to ensure load balancing on the cluster): 4 virtual cores, 15 GB ram, 8G heap size (coordinating) 
- 3 *master* node: 4 virtual cores, 15 GB ram, 8G heap size (master): not used in this scenario from our understanding 
- 15 *data* node : 8 virtual cores,  30 GB ram, 16G heap size (ingest & data) 
- Anomaly detectors: 26 running  detectors with around 500 active entities, using in total 600 MiB each

## Trying to understand the reasons behind these failures, we came up with different questions : 
1. How is the load balancing done between several node coordinators?  Is the heap percentage supposedly equally distributed between all the coordinator nodes? 
2. How are the coordinator nodes linked with the anomaly detector plugin? Is the coordinator node responsible for distributing the trees on different shards? where are the trees of the Random Cut Forest saved? Is the coordinator node responsible for collecting and aggregating the final result like the anomaly grade? 
![](https://i.imgur.com/IGU79RM.png)
When many detectors are launched the heap memory (here: 75% and 80%) of the coordinator nodes have increased greatly. How would we need to scale the coordinator node, to keep up with the demands? Adding more coordinator nodes? increasing the heap size? having more CPU(s) cores? … 
3. Reducing the batched size can be used as a protection mechanism and reduce the memory overhead per search request. Would this be helpful in the case of detectors as well? 
4. Since the detectors are configured on indexes using rollover we tried to use only the current write index (to reduce heap space errors). But detectors using write alias take 10x more time to initialize than detectors using indexes. Do you have any recommendations on this?

My team and I would be very grateful for the time you take answering all these questions.

**Comment by kaituo** [comment]
1. When you say coordinating node, do you mean a node role? I cannot find it in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.htmlIn AD, we have coordinating nodes and model nodes. Coordinating nodes are responsible for querying for features, sending features to model nodes, and producing the final result. Model nodes take care of everything related to rcf models. 

2. Could you provide a complete stack trace for java.lang.OutOfMemoryError?

3. > How is the load balancing done between several node coordinators? Is the heap percentage supposedly equally distributed between all the coordinator nodes?

Statistically, that's true. 

4. > How are the coordinator nodes linked with the anomaly detector plugin? Is the coordinator node responsible for distributing the trees on different shards? where are the trees of the Random Cut Forest saved? Is the coordinator node responsible for collecting and aggregating the final result like the anomaly grade?

Every node has an AD plugin installed. A coordinator node queries for features and distributes features to each model node (any node with models hosted in memory). The coordinating node does not distribute trees but distributes features (i.e., what you configured for a detector like max cpu) in each detection interval. The trees are hosted in memory and have checkpoints on disk. Yes, the coordinator node is responsible for collecting and aggregating the final result like the anomaly grade.

> When many detectors are launched the heap memory (here: 75% and 80%) of the coordinator nodes have increased greatly. How would we need to scale the coordinator node, to keep up with the demands? Adding more coordinator nodes? increasing the heap size? having more CPU(s) cores? …

How many shards does the index .opendistro-anomaly-detector-jobs have? I suppose it is 10? Increase heap size and having more CPUs help. I'll answer your "adding more coordinator nodes" question when you tell me what you mean by "coordinator nodes."

5.> Reducing the batched size can be used as a protection mechanism and reduce the memory overhead per search request. Would this be helpful in the case of detectors as well?

The reducing batch size tip is great, but we don't expose such details to users. We will consider that in our next release.

6. > Since the detectors are configured on indexes using rollover we tried to use only the current write index (to reduce heap space errors). But detectors using write alias take 10x more time to initialize than detectors using indexes. Do you have any recommendations on this?

AD detectors need some historical data (135 continuous intervals) for training. Otherwise, it will use live data to initialize (thus slow). When you start the detector, the index that the alias pointed to might not have much data. So 10X more time happens. One thing you can do is to start the detector when you are sure the index has data in at least 135 continuous intervals (the interval you specified when you define a detector). Then the detector can finish training quickly.

**Comment by Kerudal** [comment]
Hello Kaituo, 

Thank you very much for taking the time to answer all our questions with such details. This is very helpful. 

> When you say coordinating node, do you mean a node role? I cannot find it

The name for the node was found in open distro documentation, in Elasticsearch => Cluster Formation [link](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/cluster/). If I understood correctly there is three major types of role: master node, data node, and coordinator node. 

The node coordinator I'm talking about is the node with this type of configuration : 
```
node.master: false
node.data: false
node.ingest: false
```
These Elasticsearch instances are installed on the same VMs as Kibana(s) to ensure load balancing (this is the recommendation: https://www.elastic.co/guide/en/kibana/current/production.html)

I wasn't able to find the specific model node you're talking about. Would the configuration resemble the one of a data node? 

> Could you provide a complete stack trace for java.lang.OutOfMemoryError?

Here are two different logs that I saved, when I encountered the error with an out-of-memory error. Sadly, all other logs have been deleted. The most relevant one I had was in the first posted message. 

I would also like to add if it can help anyone: the `jvm.options` was configured to save the memory when an out-of-memory error was encountered. This took a lot of space on the disk until everything was taken and nothing could work. 

```log 
[2021-02-25T12:35:53,936][ERROR][c.a.o.s.l.p.RestSqlAction] [KBN_0] a0461897-fe5d-4cef-b597-38a1c96928aa Client side error during query execution 
[2021-02-25T12:38:00,155][ERROR][c.a.o.s.l.p.RestSqlAction] [KBN_0] 0c1a93e1-5ebd-44af-b867-322ca806b950 Client side error during query execution 
[2021-02-25T15:24:33,691][WARN ][r.suppressed ] [KBN_0] path: /_opendistro/_anomaly_detection/detectors/f0rJ2XcBcaTWr8cMkeo_/_profile/init_progress,state,error, params: {detectorID=f0rJ2XcBcaTWr8cMkeo_, type=init_progress,state,error} 
[2021-02-25T15:24:35,358][WARN ][r.suppressed ] [KBN_0] path: /_opendistro/_anomaly_detection/detectors/f0rJ2XcBcaTWr8cMkeo_/_profile/init_progress,state,error, params: {detectorID=f0rJ2XcBcaTWr8cMkeo_, type=init_progress,state,error} 
[2021-02-25T15:24:36,511][WARN ][r.suppressed ] [KBN_0] path: /_opendistro/_anomaly_detection/detectors/f0rJ2XcBcaTWr8cMkeo_/_profile/init_progress,state,error, params: {detectorID=f0rJ2XcBcaTWr8cMkeo_, type=init_progress,state,error} 
[2021-02-25T15:25:53,704][WARN ][r.suppressed ] [KBN_0] path: /_opendistro/_anomaly_detection/detectors/f0rJ2XcBcaTWr8cMkeo_/_profile/init_progress,state,error, params: {detectorID=f0rJ2XcBcaTWr8cMkeo_, type=init_progress,state,error} 
[2021-02-25T15:35:27,714][ERROR][o.e.ExceptionsHelper ] [KBN_0] fatal error 
[2021-02-25T15:35:27,717][ERROR][o.e.ExceptionsHelper ] [KBN_0] fatal error 
[2021-02-25T15:35:27,746][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [KBN_0] fatal error in thread [Thread-9], exiting 
[2021-02-25T15:35:27,746][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [KBN_0] fatal error in thread [Thread-10], exiting 
```
```log 
[2021-03-01T10:47:36,871][INFO ][c.a.o.e.p.w.EventLogQueueProcessor] [KBN_1] UNEXPECTED entry (/dev/shm/performanceanalyzer/1614595500000/heap_metrics) with epoch '1614595500000' arrived when the current bucket is '1614595650000' 
[2021-03-01T10:48:08,201][INFO ][o.e.e.NodeEnvironment ] [KBN_1] heap size [7.9gb], compressed ordinary object pointers [true] 
[2021-03-01T10:48:22,217][INFO ][c.a.o.s.a.i.AuditLogImpl ] [KBN_1] Auditing diffs for write requests is disabled. 
[2021-03-01T10:48:22,217][INFO ][c.a.o.s.a.i.AuditLogImpl ] [KBN_1] Auditing write operation requests from kibanaserver users is disabled. 
[2021-03-01T10:48:22,217][INFO ][c.a.o.s.a.i.AuditLogImpl ] [KBN_1] Auditing will watch <NONE> for write requests. 
[2021-03-01T10:48:22,218][INFO ][c.a.o.s.a.i.AuditLogImpl ] [KBN_1] .opendistro_security is used as internal security index. 
[2021-03-01T10:48:22,218][INFO ][c.a.o.s.a.i.AuditLogImpl ] [KBN_1] Internal index used for posting audit logs is null 
[2021-03-01T10:48:22,219][WARN ][c.a.o.s.c.ConfigurationRepository] [KBN_1] Following keys [opendistro_security.audit.config.disabled_rest_categories, opendistro_security.audit.config.disabled_transport_categories] are deprecated in elasticsearch settings. They will be removed in plugin v2.0.0.0 
[2021-03-01T10:48:22,219][WARN ][c.a.o.s.c.ConfigurationRepository] [KBN_1] Audit configuration settings found in both index and elasticsearch settings (deprecated) 
[2021-03-01T10:48:22,219][INFO ][c.a.o.s.c.ConfigurationRepository] [KBN_1] Hot-reloading of audit configuration is enabled[2021-03-01T10:48:22,219][INFO ][c.a.o.s.c.ConfigurationRepository] [KBN_1] Node 'KBN_1' initialized 
[2021-03-01T10:48:23,490][WARN ][c.a.o.e.p.c.s.h.ConfigOverridesClusterSettingHandler] [KBN_1] Config override setting update called with empty string. Ignoring. 
[2021-03-01T10:48:47,538][WARN ][c.a.o.s.a.BackendRegistry] [KBN_1] Authentication finally failed for null from 10.9.42.254:54376 
[2021-03-01T10:48:51,057][INFO ][o.e.m.j.JvmGcMonitorService] [KBN_1] [gc][36] overhead, spent [442ms] collecting in the last [1.2s] 
```
> How many shards does the index .opendistro-anomaly-detector-jobs have? I suppose it is 10? 

Yes, we have the default max primary shards configuration : `"max_primary_shards" : "10"` . Thank you for this precision. This will be very useful when we want more detectors with high cardinality.

**Comment by kaituo** [comment]
1. Can you run _cat/shards and [stats API](https://opendistro.github.io/for-elasticsearch-docs/docs/ad/api/#get-detector-stats) to see if any model or shard landed on the coordinating nodes?

2.
> I wasn't able to find the specific model node you're talking about. Would the configuration resemble the one of a data node?

You can run stats API as showed above.  Any node with models are model nodes.

3. One suspicion I have is: we incorrectly put models on the coordinating nodes.  We should only put models on data nodes.  Your help on 1. and 2. can confirm that.

**Comment by Kerudal** [comment]
Hi, 

> Can you run _cat/shards and stats API to see if any model or shard landed on the coordinating nodes?

Running `GET _cat/shards` : 
```
index                                                shard prirep state          docs    store ip          node
.opendistro-anomaly-detector-jobs                    1     p      STARTED           6   38.7kb x.x.x.x ES_DATA_11
.opendistro-anomaly-detector-jobs                    1     r      STARTED           6   38.7kb x.x.x.x ES_DATA_13
.opendistro-anomaly-detector-jobs                    2     r      STARTED           2    8.2kb x.x.x.x ES_DATA_7
.opendistro-anomaly-detector-jobs                    2     p      STARTED           2    8.2kb x.x.x.x ES_DATA_9
.opendistro-anomaly-detector-jobs                    3     p      STARTED           4   39.3kb x.x.x.x ES_DATA_6
.opendistro-anomaly-detector-jobs                    3     r      STARTED           4   39.3kb x.x.x.x ES_DATA_12
.opendistro-anomaly-detector-jobs                    0     p      STARTED           2    8.2kb x.x.x.x ES_DATA_1
.opendistro-anomaly-detector-jobs                    0     r      STARTED           2    8.2kb x.x.x.x ES_DATA_10
.opendistro-anomaly-checkpoints                      1     p      STARTED        7376      1gb x.x.x.x ES_DATA_11
.opendistro-anomaly-checkpoints                      1     r      STARTED        7376 1008.1mb x.x.x.x ES_DATA_14
.opendistro-anomaly-checkpoints                      2     p      STARTED        7708  790.6mb x.x.x.x ES_DATA_0
.opendistro-anomaly-checkpoints                      2     r      STARTED        7708      1gb x.x.x.x ES_DATA_10
.opendistro-anomaly-checkpoints                      3     r      STARTED        7450  910.8mb x.x.x.x ES_DATA_6
.opendistro-anomaly-checkpoints                      3     p      STARTED        7450    1.1gb x.x.x.x ES_DATA_9
.opendistro-anomaly-checkpoints                      0     r      STARTED        7272  983.1mb x.x.x.x ES_DATA_4
.opendistro-anomaly-checkpoints                      0     p      STARTED        7272  791.2mb x.x.x.x ES_DATA_7
.opendistro-anomaly-results-history-2021.03.02-1     1     r      STARTED     1535231   85.3mb x.x.x.x ES_DATA_12
.opendistro-anomaly-results-history-2021.03.02-1     1     p      STARTED     1535231   81.8mb x.x.x.x ES_DATA_4
.opendistro-anomaly-results-history-2021.03.02-1     2     p      STARTED     1541589   80.2mb x.x.x.x ES_DATA_0
.opendistro-anomaly-results-history-2021.03.02-1     2     r      STARTED     1545972   79.7mb x.x.x.x ES_DATA_11
.opendistro-anomaly-results-history-2021.03.02-1     3     r      STARTED     1539366   87.4mb x.x.x.x ES_DATA_6
.opendistro-anomaly-results-history-2021.03.02-1     3     p      STARTED     1535738   84.7mb x.x.x.x ES_DATA_10
.opendistro-anomaly-results-history-2021.03.02-1     0     r      STARTED     1540024   98.6mb x.x.x.x ES_DATA_14
.opendistro-anomaly-results-history-2021.03.02-1     0     p      STARTED     1540024   79.8mb x.x.x.x ES_DATA_1
.opendistro-anomaly-detectors                        0     r      STARTED          26   84.9kb x.x.x.x ES_DATA_11
.opendistro-anomaly-detectors                        0     p      STARTED          26   84.9kb x.x.x.x ES_DATA_13
.opendistro-anomaly-detection-state                  0     r      STARTED           7   38.1kb x.x.x.x ES_DATA_1
.opendistro-anomaly-detection-state                  0     p      STARTED           7   45.2kb x.x.x.x ES_DATA_13
```

Running `GET _opendistro/_anomaly_detection/stats` : 
```
{
  "anomaly_detectors_index_status" : "green",
  "anomaly_detection_state_status" : "green",
  "detector_count" : 7,
  "anomaly_detection_job_index_status" : "green",
  "models_checkpoint_index_status" : "green",
  "anomaly_results_index_status" : "green",
  "nodes" : {
    "spyA3dLrQ0uxhoRlTzP_VQ" : {
      "ad_execute_request_count" : 397,
      "ad_execute_failure_count" : 42,
      "models" : [
        {
          "detector_id" : "sRHiAngBgHe6lezYc1ML",
          "model_type" : "entity",
          "model_id" : "sRHiAngBgHe6lezYc1ML_entity_x.x.x.x"
        },
        {
          "detector_id" : "sRHiAngBgHe6lezYc1ML",
          "model_type" : "entity",
          "model_id" : "sRHiAngBgHe6lezYc1ML_entity_x.x.x.x"
        },
        {
          "detector_id" : "sRHiAngBgHe6lezYc1ML",
          "model_type" : "entity",
          "model_id" : "sRHiAngBgHe6lezYc1ML_entity_x.x.x.x"
        },
        {
          "detector_id" : "sRHiAngBgHe6lezYc1ML",
          "model_type" : "entity",
          "model_id" : "sRHiAngBgHe6lezYc1ML_entity_x.x.x.x"
        },
        //...
      ],
      "ad_hc_execute_request_count" : 0,
      "ad_hc_execute_failure_count" : 0
    }
  }
}
```

> You can run stats API as showed above. Any node with models are model nodes. 

Thank you for the advice. Running this command : 
```
GET _opendistro/_anomaly_detection/KBN_0/stats
GET _opendistro/_anomaly_detection/KBN_1/stats
---------------------------------------------------------
{
  "anomaly_detectors_index_status" : "green",
  "anomaly_detection_state_status" : "green",
  "detector_count" : 7,
  "anomaly_detection_job_index_status" : "green",
  "models_checkpoint_index_status" : "green",
  "anomaly_results_index_status" : "green",
  "nodes" : {
    "7OLSDinQRvG3qKio-mePCA" : {
      "ad_execute_request_count" : 0,
      "ad_execute_failure_count" : 0,
      "models" : [ ],
      "ad_hc_execute_request_count" : 0,
      "ad_hc_execute_failure_count" : 0
    }
  }
}
```
Confirms that both coordinator nodes are not used as model nodes.
```
GET _opendistro/_anomaly_detection/ES_DATA_2/stats
```
The ones we called data nodes, do play the role of model nodes since they contain models. 

>  From what you provided, I cannot confirm that. It would be great if you can give us the complete trace related to:

I'm sorry. I'll try to have better logs. Right now everything is running correctly but when this problem is encountered again, I'll post a new message with more explicit logs. 

> Increasing disk space is the only solution :) 

Thank you, we actually decided not to save the memory.

**Comment by kaituo** [comment]
Thanks for confirming 👍 

Heap dump will be useful for debugging memory issues. Still suggest we should save the heap dump.

**Comment by Kerudal** [comment]
Hi Kaituo, 

Thank you again for taking the time to answer our questions. Your answers were very helpful for us to understand the plugin more deeply.

**Comment by kaituo** [comment]
Hi Kerudal, you are welcome.  Can we have a call?  We want to have a better understanding of your use case.

**Comment by Kerudal** [comment]
Hi Kaituo, 

Right now the problem has been fixed, and our detectors are running correctly. 
We are available for a call, to discuss the case and the architecture put in place. We are located in France, would it be possible to have a call around 9 or 10 a.m your time?

**Comment by kaituo** [comment]
Hi Kerudal, would next Wednesday (Mar 24) 9~10 a.m. PST works?  Do you guys use Amazon Chime or Zoom? Please give us your email as well.

**Comment by Kerudal** [comment]
Hi Kaituo, 

Wednesday (Mar 24) sounds great for us for 9 a.m PST. Our emails are : 
- allairefloriane@gmail.com 
- julien.elkhiati@gmail.com 
We can use zoom for the call or even skype

**Comment by kaituo** [comment]
Just realized I don't have zoom license to host a meeting.  Do you guys have license?  If no, I can create Amazon Chime meeting or try Skype (haven't used it for a while).

**Comment by Kerudal** [comment]
Hi Kaituo, 

We do not have a license for zoom but we can use Amazon Chime. 
Thank you for your address

**Comment by kaituo** [comment]
got your invitation using google meet.  Talk to you next week.

**Comment by ylwu-amzn** [comment]
Close this issue as user's issue gone.
