### ISSUE TITLE
Documentation for cluster:admin/ad/* permissions

### ISSUE THREAD

**Issue by Tarasovych** [opendistro-for-elasticsearch/anomaly-detection#400]
Hi! I'd like to see a word about `cluster:admin/ad/*` in the docs. I figured it out, that this permission is required for listing anomaly detectors in Kibana. Anyway, I didn't find `cluster:admin/ad/*` on https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/permissions/
Thank you!

**Comment by kaituo** [comment]
I'll add the list of ad permission to the page you requested.  For "this permission is required for listing anomaly detectors in Kibana", do you think https://opendistro.github.io/for-elasticsearch-docs/docs/ad/security/ is good enough?
