### ISSUE TITLE
Anaomly Detection Plugin Setup on Container

### ISSUE THREAD

**Issue by redhawk19** [opendistro-for-elasticsearch/anomaly-detection#85]
Hi, I have setup a docker cluster of elasticsearch open distro, Please let me know How to install anomaly detection on docker containers ?

**Comment by redhawk19** [comment]
Anyone please share the steps ? As I have followed but getting issue ?

**Comment by ylwu-amzn** [comment]
Have you tried this https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/ ?

**Comment by yizheliu-amazon** [comment]
Will close it as there is no response after over 3 months
